//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseCnX.DbEntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ecommerceEntities : DbContext
    {
        public ecommerceEntities()
            : base("name=ecommerceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ARTICLE> ARTICLES { get; set; }
        public virtual DbSet<CATEGORIE> CATEGORIEs { get; set; }
        public virtual DbSet<PROFIL> PROFILs { get; set; }
        public virtual DbSet<QUESTIONSECRET> QUESTIONSECRETs { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
    }
}
