//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseCnX.DbEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROFIL
    {
        public int idprofil { get; set; }
        public string username { get; set; }
        public string adresse { get; set; }
        public string ville { get; set; }
        public string pays { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
